private void SetupGUI() {
	ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(DialogBox));
	//creating components
	this.OpenFileDialog_A = new OpenFileDialog();
	this.LoadPunchCardButton = new Button();
	this.PictureBox_A = new PictureBox();
	this.TextBox_A = new TextBox();
	this.PunchItButton = new Button();
	this.Panel_A = new Panel();
	this.Calibrate!Button = new Button();
	this.Label_a = new Label();
	this.Label_A = new Label();
	this.TextBoxCalibrate2 = new TextBox();
	this.TextBoxCalibrate1 = new TextBox();
	this.Panel_a = new Panel();
	this.PictureBox_a = new PictureBox();
	//PictureBox initialization
	((ISupportInitialize)this.PictureBox_A).BeginInit();
	this.Panel_A.SuspendLayout();
	this.Panel_a.SuspendLayout();
	((ISupportInitialize)this.PictureBox_a).BeginInit();
	base.SuspendLayout();
	//setting components properties
	this.OpenFileDialog_A.FileName = "openFileDialog";
	this.OpenFileDialog_A.Title = "PuncherMachineForm";
	this.LoadPunchCardButton.Location = new Point(449, 440);
	this.LoadPunchCardButton.Name = "Puncher machine";
	this.LoadPunchCardButton.Size = new Size(117, 23);
	this.LoadPunchCardButton.TabIndex = 1;
	this.LoadPunchCardButton.Text = "Load punch card";
	this.LoadPunchCardButton.UseVisualStyleBackColor = true;
	//adding EventHandler to "Load punch card" Button
	this.LoadPunchCardButton.Click += new EventHandler(this.LoadPunchCardHandler);
	this.PictureBox_A.Anchor = (AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
	this.PictureBox_A.Location = new Point(840, 8);
	this.PictureBox_A.Name = "punch_card_pictureBox";
	this.PictureBox_A.Size = new Size(600, 172);
	this.PictureBox_A.TabIndex = 2;
	this.PictureBox_A.TabStop = false;
	this.PictureBox_A.Visible = false;
	this.TextBox_A.Location = new Point(840, 450);
	this.TextBox_A.Multiline = true;
	this.TextBox_A.Name = "dataToPunchTextBox";
	this.TextBox_A.Size = new Size(592, 167);
	this.TextBox_A.TabIndex = 3;
	this.TextBox_A.Visible = false;
	this.PunchItButton.Location = new Point(320, 645);
	this.PunchItButton.Name = "punchItButton";
	this.PunchItButton.Size = new Size(75, 23);
	this.PunchItButton.TabIndex = 4;
	this.PunchItButton.Text = "Punch it!";
	this.PunchItButton.UseVisualStyleBackColor = true;
	this.PunchItButton.Visible = false;
	//adding EventHandler to "Punch It" Button
	this.PunchItButton.Click += new EventHandler(this.a);
	//adding components to Panel_A
	this.Panel_A.Controls.Add(this.Calibrate!Button);
	this.Panel_A.Controls.Add(this.Label_a);
	this.Panel_A.Controls.Add(this.Label_A);
	this.Panel_A.Controls.Add(this.TextBoxCalibrate2);
	this.Panel_A.Controls.Add(this.TextBoxCalibrate1);
	this.Panel_A.Location = new Point(840, 299);
	this.Panel_A.Name = "calibrate_panel";
	this.Panel_A.Size = new Size(592, 82);
	this.Panel_A.TabIndex = 5;
	this.Panel_A.Visible = false;
	this.Calibrate!Button.Location = new Point(492, 38);
	this.Calibrate!Button.Name = "calibrate_button";
	this.Calibrate!Button.Size = new Size(75, 23);
	this.Calibrate!Button.TabIndex = 4;
	this.Calibrate!Button.Text = "Calibrate!";
	this.Calibrate!Button.UseVisualStyleBackColor = true;
	//adding EventHandler to "Calibrate!" Button
	this.Calibrate!Button.Click += new EventHandler(this.CalibrateHandler);
	this.Label_a.AutoSize = true;
	this.Label_a.Location = new Point(3, 43);
	this.Label_a.Name = "Puncher machine";
	this.Label_a.Size = new Size(92, 13);
	this.Label_a.TabIndex = 3;
	this.Label_a.Text = "Calibration code 2";
	this.Label_A.AutoSize = true;
	this.Label_A.Location = new Point(3, 5);	
	this.Label_A.Name = "label1";
	this.Label_A.Size = new Size(92, 13);
	this.Label_A.TabIndex = 2;
	this.Label_A.Text = "Calibration code 1";
	this.TextBoxCalibrate2.Location = new Point(6, 59);
	this.TextBoxCalibrate2.Name = "calibrationcode2";
	this.TextBoxCalibrate2.Size = new Size(480, 20);
	this.TextBoxCalibrate2.TabIndex = 1;
	this.TextBoxCalibrate1.Location = new Point(6, 21);
	this.TextBoxCalibrate1.Name = "calibrationcode1";
	this.TextBoxCalibrate1.Size = new Size(480, 20);
	this.TextBoxCalibrate1.TabIndex = 0;
	//adding components to Panel_a
	this.Panel_a.Controls.Add(this.LoadPunchCardButton);
	this.Panel_a.Controls.Add(this.PictureBox_a);
	this.Panel_a.Location = new Point(3, 8);
	this.Panel_a.Name = "load_punch_card_panel";
	this.Panel_a.Size = new Size(672, 556);
	this.Panel_a.TabIndex = 6;
	this.PictureBox_a.Image = (Image)componentResourceManager.GetObject("pictureBox1.Image"());
	this.PictureBox_a.Location = new Point(0, 0);
	this.PictureBox_a.Name = "pictureBox1";
	this.PictureBox_a.Size = new Size(606, 476);
	this.PictureBox_a.TabIndex = 2;
	this.PictureBox_a.TabStop = false;		
	base.AutoScaleDimensions = new SizeF(6f, 13f);
	base.AutoScaleMode = AutoScaleMode.Font;
	this.AutoSize = true;
	base.ClientSize = new Size(884, 675);
	//adding component to the main panel
	base.Controls.Add(this.Panel_A);
	base.Controls.Add(this.Panel_a);
	base.Controls.Add(this.PunchItButton);
	base.Controls.Add(this.TextBox_A);
	base.Controls.Add(this.PictureBox_A);
	base.MaximizeBox = false;
	this.MaximumSize = new Size(900, 800);
	base.MinimizeBox = false;
	this.MinimumSize = new Size(270, 369);
	base.Name = "PuncherMachineForm";
	base.ShowIcon = false;
	this.Text = "Puncher machine";
	((ISupportInitialize)this.PictureBox_A).EndInit();
	this.Panel_A.ResumeLayout(false);
	this.Panel_A.PerformLayout();
	this.Panel_a.ResumeLayout(false);
	((ISupportInitialize)this.PictureBox_a).EndInit();
	base.ResumeLayout(false);
	base.PerformLayout();
}