public b(string text, byte[] first, Assembly assembly, b.A a)
{
				byte[] second = c.A(text);
				byte[] second;
if(((!first.SequenceEqual(second))
{
	throw new C(.n());
	IL_1296:
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	throw new C(.n());
	IL_1296:
	this.a = new SoundPlayer(H.b());
	throw new C(.n());
	IL_1296:
	this.a = new SoundPlayer(H.b());
	throw new C(.n());
	IL_1296:
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
}
else
{
				this.A = a;
				this.A = new Bitmap(text, true);
				this.A = new List<char>();
				this.A.Add('0');
				this.A.Add('1');
				this.A.Add('2');
				this.A.Add('3');
				this.A.Add('4');
				this.A.Add('5');
				this.A.Add('6');
				this.A.Add('7');
				this.A.Add('8');
				this.A.Add('9');
				this.A.Add('A');
				this.A.Add('B');
				this.A.Add('C');
				this.A.Add('D');
				this.A.Add('E');
				this.A.Add('F');
				this.A.Add('G');
				this.A.Add('H');
				this.A.Add('I');
				this.A.Add('J');
				this.A.Add('K');
				this.A.Add('L');
				this.A.Add('M');
				this.A.Add('N');
				this.A.Add('O');
				this.A.Add('P');
				this.A.Add('Q');
				this.A.Add('R');
				this.A.Add('/');
				this.A.Add('S');
				this.A.Add('T');
				this.A.Add('U');
				this.A.Add('V');
				this.A.Add('W');
				this.A.Add('X');
				this.A.Add('Y');
				this.A.Add('Z');
				this.A.Add('a');
				this.A.Add('b');
				this.A.Add('c');
				this.A.Add('d');
				this.A.Add('e');
				this.A.Add('f');
				this.A.Add('g');
				this.A.Add('h');
				this.A.Add('i');
				this.A.Add('j');
				this.A.Add('k');
				this.A.Add('l');
				this.A.Add('m');
				this.A.Add('n');
				this.A.Add('o');
				this.A.Add('p');
				this.A.Add('q');
				this.A.Add('r');
				this.A.Add('s');
				this.A.Add('t');
				this.A.Add('u');
				this.A.Add('v');
				this.A.Add('w');
				this.A.Add('x');
				this.A.Add('y');
				this.A.Add('z');
				this.A.Add(':');
				this.A.Add('#');
				this.A.Add('@');
				this.A.Add('\'');
				this.A.Add('=');
				this.A.Add('"');
				this.A.Add('.');
				this.A.Add('<');
				this.A.Add('(');
				this.A.Add('+');
				this.A.Add('|');
				this.A.Add('$');
				this.A.Add('*');
				this.A.Add(')');
				this.A.Add(';');
				this.A.Add(',');
				this.A.Add('%');
				this.A.Add('_');
				this.A.Add('>');
				this.A.Add('?');
				this.A.Add(' ');
				this.A.Add('-');
				this.A.Add('&');
				this.A = new List<int>();
				this.A.Add(Convert.ToInt32(.O(), 2));
				this.A.Add(Convert.ToInt32(.o(), 2));
				this.A.Add(Convert.ToInt32(.P(), 2));
				this.A.Add(Convert.ToInt32(.p(), 2));
				this.A.Add(Convert.ToInt32(.Q(), 2));
				this.A.Add(Convert.ToInt32(.q(), 2));
				this.A.Add(Convert.ToInt32(.R(), 2));
				this.A.Add(Convert.ToInt32(.r(), 2));
				this.A.Add(Convert.ToInt32(.S(), 2));
				this.A.Add(Convert.ToInt32(.s(), 2));
				this.A.Add(Convert.ToInt32(.T(), 2));
				this.A.Add(Convert.ToInt32(.t(), 2));
				this.A.Add(Convert.ToInt32(.U(), 2));
				this.A.Add(Convert.ToInt32(.u(), 2));
				this.A.Add(Convert.ToInt32(.V(), 2));
				this.A.Add(Convert.ToInt32(.v(), 2));
				this.A.Add(Convert.ToInt32(.W(), 2));
				this.A.Add(Convert.ToInt32(.w(), 2));
				this.A.Add(Convert.ToInt32(.X(), 2));
				this.A.Add(Convert.ToInt32(.x(), 2));
				this.A.Add(Convert.ToInt32(.Y(), 2));
				this.A.Add(Convert.ToInt32(.y(), 2));
				this.A.Add(Convert.ToInt32(.Z(), 2));
				this.A.Add(Convert.ToInt32(.z(), 2));
				this.A.Add(Convert.ToInt32(.aA(), 2));
				this.A.Add(Convert.ToInt32(.aa(), 2));
				this.A.Add(Convert.ToInt32(.aB(), 2));
				this.A.Add(Convert.ToInt32(.ab(), 2));
				this.A.Add(Convert.ToInt32(.aC(), 2));
				this.A.Add(Convert.ToInt32(.ac(), 2));
				this.A.Add(Convert.ToInt32(.aD(), 2));
				this.A.Add(Convert.ToInt32(.ad(), 2));
				this.A.Add(Convert.ToInt32(.aE(), 2));
				this.A.Add(Convert.ToInt32(.ae(), 2));
				this.A.Add(Convert.ToInt32(.aF(), 2));
				this.A.Add(Convert.ToInt32(.af(), 2));
				this.A.Add(Convert.ToInt32(.aG(), 2));
				this.A.Add(Convert.ToInt32(.ag(), 2));
				this.A.Add(Convert.ToInt32(.aH(), 2));
				this.A.Add(Convert.ToInt32(.ah(), 2));
				this.A.Add(Convert.ToInt32(.aI(), 2));
				this.A.Add(Convert.ToInt32(.ai(), 2));
				this.A.Add(Convert.ToInt32(.aJ(), 2));
				this.A.Add(Convert.ToInt32(.aj(), 2));
				this.A.Add(Convert.ToInt32(.aK(), 2));
				this.A.Add(Convert.ToInt32(.ak(), 2));
				this.A.Add(Convert.ToInt32(.aL(), 2));
				this.A.Add(Convert.ToInt32(.al(), 2));
				this.A.Add(Convert.ToInt32(.aM(), 2));
				this.A.Add(Convert.ToInt32(.am(), 2));
				this.A.Add(Convert.ToInt32(.aN(), 2));
				this.A.Add(Convert.ToInt32(.an(), 2));
				this.A.Add(Convert.ToInt32(.aO(), 2));
				this.A.Add(Convert.ToInt32(.ao(), 2));
				this.A.Add(Convert.ToInt32(.aP(), 2));
				this.A.Add(Convert.ToInt32(.ap(), 2));
				this.A.Add(Convert.ToInt32(.aQ(), 2));
				this.A.Add(Convert.ToInt32(.aq(), 2));
				this.A.Add(Convert.ToInt32(.aR(), 2));
				this.A.Add(Convert.ToInt32(.ar(), 2));
				this.A.Add(Convert.ToInt32(.aS(), 2));
				this.A.Add(Convert.ToInt32(.@as(), 2));
				this.A.Add(Convert.ToInt32(.aT(), 2));
				this.A.Add(Convert.ToInt32(.at(), 2));
				this.A.Add(Convert.ToInt32(.aU(), 2));
				this.A.Add(Convert.ToInt32(.au(), 2));
				this.A.Add(Convert.ToInt32(.aV(), 2));
				this.A.Add(Convert.ToInt32(.av(), 2));
				this.A.Add(Convert.ToInt32(.aW(), 2));
				this.A.Add(Convert.ToInt32(.aw(), 2));
				this.A.Add(Convert.ToInt32(.aX(), 2));
				this.A.Add(Convert.ToInt32(.ax(), 2));
				this.A.Add(Convert.ToInt32(.aY(), 2));
				this.A.Add(Convert.ToInt32(.ay(), 2));
				this.A.Add(Convert.ToInt32(.aZ(), 2));
				this.A.Add(Convert.ToInt32(.az(), 2));
				this.A.Add(Convert.ToInt32(.BA(), 2));
				this.A.Add(Convert.ToInt32(.Ba(), 2));
				this.A.Add(Convert.ToInt32(.BB(), 2));
				this.A.Add(Convert.ToInt32(.Bb(), 2));
				this.A.Add(Convert.ToInt32(.BC(), 2));
				this.A.Add(Convert.ToInt32(.Bc(), 2));
				this.A.Add(Convert.ToInt32(.BD(), 2));
				this.A.Add(Convert.ToInt32(.Bd(), 2));
				this.A.Add(Convert.ToInt32(.BE(), 2));
				this.A.Add(Convert.ToInt32(.Be(), 2));
				this.A = assembly;
				this.A = new SoundPlayer(H.B());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
	this.a = new SoundPlayer(H.b());
}
